### PR TITLE
Fix bug in the bool values parsing

### PR DESCRIPTION
**Pull request by alexk-esna**
Populating the config structure by cfgDefault values of boolean fields on the first step of parsing, before the config-file loading. The change doesn't touch fields of other types.

### CODE REVIEW

**Comment by alexk-esna** [comment]
Hi,
An attempt to move the issu43 tests to config_test.go file will give rise
the "import cycle" error:
    package github.com/crgimenes/goconfig (test)
        imports github.com/crgimenes/goconfig/ini
        imports github.com/crgimenes/goconfig
Ideas?

**Comment by crgimenes** [comment]
@alexk-esna we would need to reformulate the test to avoid cyclical import. 
 An alternative that I do not think is a bad idea is to create a directory with more generic name than the number of the issue and from there we can use to make several generic tests, not just this one.
What do you think?

**Comment by alexk-esna** [comment]
issue43/         => issues/
    bool_test.go => issues/issue43_test.go
    env.ini      => issues/fixtures/env43.ini
    env.json     => issues/fixtures/env43.json
ok?

**Comment by crgimenes** [comment]
I believe that is OK.

**Pull request merged**
